### ISSUE TITLE
Generate more meaningful stack traces with source mapping

### ISSUE THREAD

**Issue by NodeGuy** [luniehq/lunie#1451]
We concatenate our source code with Webpack, making line numbers in stack traces less meaningful, e.g.,

```
TypeError: Cannot read property 'words' of null
  at Object._doReset (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:107634:33)
  at Object.reset (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:7434:19)
  at Object.reset (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:7772:27)
  at Object.init (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:7419:19)
  at Object.subtype.init (/private/var/folders/9y/jgtj1b7n6mz2_rtg61cvdb140000gn/T/AppTranslocation/610C7176-3827-4A84-AAD2-D00C52F8CC9F/d/Cosmos%20Voyager.app/Contents/Resources/app/dist/renderer.js:6194:46)
...
(9 additional frame(s) were not displayed)
```

Use source mapping so that we can see the line numbers in the original source code.

**Comment by faboweb** [comment]
Scope:
- [ ] enable sourcemaps in webpack
- [ ] check that errors in chrome use sourcemaps
- [ ] bonus: check that errors in sentry use sourcemaps

**Comment by NodeGuy** [comment]
Another possibility to explore is whether we can get Webpack to stop concatenating the files.
