### ISSUE TITLE
Kava Internal Server Error: Error for query validatorsets

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#4352]
I am getting this in the local API:

```
newBlockHandler failed ApolloError: 500: Internal Server Error
    at KavaV1API.<anonymous> (/home/ana/lunie/lunie/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:85:25)
    at Generator.next (<anonymous>)
    at /home/ana/lunie/lunie/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/ana/lunie/lunie/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:4:12)
    at KavaV1API.errorFromResponse (/home/ana/lunie/lunie/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:75:16)
    at KavaV1API.<anonymous> (/home/ana/lunie/lunie/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:53:34)
    at Generator.next (<anonymous>)
    at /home/ana/lunie/lunie/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:8:71
    at new Promise (<anonymous>) {
  extensions: {
    code: undefined,
    response: {
      url: 'http://lcd.kava.forbole.com:1317/validatorsets/177217',
      status: 500,
      statusText: 'Internal Server Error',
      body: [Object]
    }
  }
}
```

Looking into it

**Comment by Bitcoinera** [comment]
OK, just contacted Kwun and he's looking into it 💪

**Comment by Bitcoinera** [comment]
Ok, he fixed it in less than 8 min. Some people have the gift
