### ISSUE TITLE
Bug in BalancesV2 query using a kusama stash address

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4936]
**Describe the bug**

Bug in BalancesV2 query using a kusama stash address.

**To Reproduce**

On staging API, use this query:

```
query {
  balancesV2 (address: "GTzRQPzkcuynHgkEHhsPBFpKdh4sAacVRsnd8vYfPpTMeEY", networkId: "kusama") {
    available
    total
  }
}
```

Output:

```
{
  "errors": [
    {
      "message": "Cannot read property 'active' of null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "balancesV2"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'active' of null",
            "    at polkadotAPI.getBalancesV2FromAddress (/var/www/server/lib/source/polkadotV0-source.js:249:48)",
            "    at runMicrotasks (<anonymous>)",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
            "    at async balancesV2 (/var/www/server/lib/resolvers.js:313:24)"
          ]
        }
      }
    }
  ],
  "data": {
    "balancesV2": null
  }
}
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 
 - Browser: 
 - Version: 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by mariopino** [comment]
Closing via #4934
