### ISSUE TITLE
Select / deselect validator is not working for substrate networks

### ISSUE THREAD

**Issue by mariopino** [luniehq/lunie#4938]
Select / deselect validator is not working for substrate networks

**Comment by mariopino** [comment]
Stack:

```
0: "TypeError: Cannot read property 'nominations' of undefined"
1: "    at polkadotAPI.getDelegationForValidator (/var/www/server/lib/source/polkadotV0-source.js:579:32)"
2: "    at runMicrotasks (<anonymous>)"
3: "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```
