### ISSUE TITLE
ScriptRunner is failing

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie#5121]
Seems to be essentially a connection issue. Here some logs from Grafana:

```
	2020-10-16 18:00:13	
FetchError: request to https://production-db.lunie.io/v1/graphql failed, reason: getaddrinfo EAI_AGAIN production-db.lunie.io
2020-10-16 17:58:54	
at async /scriptRunner/src/keybase.js:11:24
2020-10-16 17:58:54	
at async Object.read (/api/lib/database/helpers.js:162:17)
2020-10-16 17:58:54	
at async /api/lib/database/helpers.js:6:16
2020-10-16 17:58:54	
at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-10-16 17:58:54	
at runMicrotasks (<anonymous>)
2020-10-16 17:58:54	
at /api/lib/database/helpers.js:23:13
2020-10-16 17:58:54	
Error: GraphQL query failed
2020-10-16 17:58:54	
}
2020-10-16 17:58:54	
}
2020-10-16 17:58:54	
profile_identifier
2020-10-16 17:58:54	
last_updated
2020-10-16 17:58:54	
name
2020-10-16 17:58:54	
operator_address
2020-10-16 17:58:54	
terra_mainnet_validatorprofiles {
2020-10-16 17:58:54	
query terra_mainnet_validatorprofiles {
2020-10-16 17:58:52	
DB read failed for query
2020-10-16 17:58:35	
}
2020-10-16 17:58:35	
}
2020-10-16 17:58:35	
profile_identifier
2020-10-16 17:58:35	
last_updated
2020-10-16 17:58:35	
name
2020-10-16 17:58:35	
operator_address
2020-10-16 17:58:35	
terra_mainnet_validatorprofiles {
2020-10-16 17:58:35	
query terra_mainnet_validatorprofiles {
2020-10-16 17:58:35	
}
2020-10-16 17:58:35	
code: 'EAI_AGAIN'
2020-10-16 17:58:35	
errno: 'EAI_AGAIN',
2020-10-16 17:58:35	
type: 'system',
2020-10-16 17:58:35	
at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2020-10-16 17:58:35	
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
2020-10-16 17:58:35	
at emitErrorNT (internal/streams/destroy.js:106:8)
2020-10-16 17:58:35	
at TLSSocket.EventEmitter.emit (domain.js:486:12)
2020-10-16 17:58:35	
at TLSSocket.emit (events.js:314:20)
2020-10-16 17:58:35	
at TLSSocket.socketErrorListener (_http_client.js:469:9)
2020-10-16 17:58:35	
at ClientRequest.EventEmitter.emit (domain.js:486:12)
2020-10-16 17:58:35	
at ClientRequest.emit (events.js:326:22)
2020-10-16 17:58:35	
at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1461:11)
2020-10-16 17:58:35	
FetchError: request to https://production-db.lunie.io/v1/graphql failed, reason: getaddrinfo EAI_AGAIN production-db.lunie.io
2020-10-16 17:49:11	
2020-10-16 15:48:58 API-WS: disconnected from wss://lunie-wss.kusama.fish: 1006:: connection failed
2020-10-16 17:47:59	
2020-10-16 15:47:19 API-WS: disconnected from wss://lunie-wss.kusama.fish: 1006:: connection failed
2020-10-16 17:47:59	
2020-10-16 15:45:56 API-WS: disconnected from wss://lunie-wss.kusama.fish: 1006:: connection failed
2020-10-16 17:45:37	
2020-10-16 15:45:17 API-WS: disconnected from wss://lunie-wss.kusama.fish: 1006:: Connection dropped by remote peer.
2020-10-16 17:44:43	
loading exposure for era 130: 3.505s
2020-10-16 17:44:40	
loading exposure for era 129: 3.585s
2020-10-16 17:44:36	
loading exposure for era 128: 3.553s
2020-10-16 17:44:32	
loading exposure for era 127: 4.015s
2020-10-16 17:44:28	
loading exposure for era 126: 3.772s
2020-10-16 17:44:25	
loading exposure for era 125: 3.784s
2020-10-16 17:44:21	
loading exposure for era 124: 4.095s
2020-10-16 17:44:17	
loading exposure for era 123: 3.752s
2020-10-16 17:44:13	
loading exposure for era 122: 3.453s
2020-10-16 17:44:09	
loading exposure for era 121: 3.650s
2020-10-16 17:44:06	
loading exposure for era 120: 12.429s
2020-10-16 17:43:53	
loading exposure for era 119: 12.103s
2020-10-16 17:43:41	
loading exposure for era 118: 10.003s
2020-10-16 17:43:32	
2020-10-16 15:43:32 API-WS: disconnected from wss://lunie-wss.kusama.fish: 1006:: Connection dropped by remote peer.
2020-10-16 17:43:31	
loading exposure for era 117: 9.933s
2020-10-16 17:43:21	
loading exposure for era 116: 9.759s
2020-10-16 17:43:12	
loading exposure for era 115: 9.288s
```

**Comment by Bitcoinera** [comment]
Fixed by #5135

**Comment by Bitcoinera** [comment]
Seems it is still broken...

**Comment by Bitcoinera** [comment]
OK, it is just missing the env variables required for the FiatValuesAPI

```
EMONEY_EXCHANGE_API_RATES_ENDPOINT
EMONEY_API_MAINNET
EMONEY_API_TESTNET
```

**Comment by faboweb** [comment]
why are we needing those? the fiatvaluesapi shouldn't fail if those are missing. let's handle the case that those values are missing.

**Comment by Bitcoinera** [comment]
OK :ok_hand:

**Comment by mariopino** [comment]
Closing via #5144
